input {
  file {
    path => "/usr/share/logstash/logs/finance-portal*.log"
    start_position => "beginning"
    codec => "json"
  }
}

output {
  opensearch {
    # DİKKAT: finance_opensearch yerine sadece opensearch yazdık!
    hosts => ["http://opensearch:9200"]
    index => "finance-logs-%{+YYYY.MM.dd}"
  }
}