input {
  kafka {
    bootstrap_servers => "finance-kafka:29092"
    topics => ["finance-app-logs"]
    codec => "json"
    group_id => "finance-logstash-group"
  }
}

output {
  opensearch {
    hosts => ["http://finance-opensearch:9200"]
    index => "finance-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}