###

### Keycloak'tan Access Token Al (Bu işlemi 1 kez çalıştırıp token almalısın)
POST http://localhost:8080/realms/finance-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=admin-cli&username=superadmin&password=superadmin&grant_type=password

> {%
    // Aldığımız Token'ı bir değişkene atıyoruz ki diğer isteklerde otomatik kullanabilelim
    client.global.set("auth_token", response.body.access_token);
%}

